# Generated by Django 5.0.4 on 2024-04-10 21:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('summary', models.CharField()),
                ('description', models.TextField()),
                ('reference', models.CharField(max_length=10, unique=True)),
                ('typeBusiness', models.CharField(choices=[('rent', 'Alquilar'), ('sell', 'Vender'), ('transfer', 'Traspasar')], max_length=10)),
                ('typeHouse', models.CharField(choices=[('Pisos', [('piso', 'Piso'), ('atico', 'Atico'), ('duplex', 'Duplex')]), ('Casas y Chalets', [('independiente', 'Independiente'), ('pareado', 'Pareado'), ('adosada', 'Adosada'), ('casa_rustica', 'Casa rustica')]), ('Comerciales', [('trastero', 'Trastero'), ('local_comercial', 'Local Comercial')])], max_length=15)),
                ('price', models.FloatField()),
                ('metrosUtiles', models.FloatField()),
                ('metrosConstruidos', models.FloatField()),
                ('numBedrooms', models.PositiveIntegerField()),
                ('numBathrooms', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('new', 'Obra nueva'), ('good', 'Buen estado'), ('bad', 'A reformar')], max_length=14)),
                ('floor', models.CharField(choices=[('last', 'Ultima'), ('middle', 'Intermedias'), ('ground', 'Baja')], max_length=12)),
                ('publishedDate', models.DateField(default=datetime.date(2024, 4, 10))),
                ('address', models.CharField()),
                ('zipCode', models.IntegerField()),
                ('city', models.CharField()),
                ('country', models.CharField()),
            ],
        ),
    ]
