# Generated by Django 5.0.4 on 2024-04-10 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='publishedDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
