# Generated by Django 5.0.4 on 2024-04-23 09:10

import django.db.models.deletion
import realEstate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OfficeImage',
            new_name='ImageOffice',
        ),
        migrations.AlterModelOptions(
            name='imageoffice',
            options={},
        ),
        migrations.RenameField(
            model_name='imageoffice',
            old_name='office',
            new_name='relatedOffice',
        ),
        migrations.CreateModel(
            name='ImageHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=realEstate.models.uploadHouseFile)),
                ('relatedHouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='realEstate.house')),
            ],
        ),
        migrations.DeleteModel(
            name='HouseImage',
        ),
    ]
