# Generated by Django 5.0.4 on 2024-04-11 22:37

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0003_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=120)),
                ('number', models.CharField(max_length=20)),
                ('localidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='agent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='realEstate.agent'),
        ),
        migrations.AddField(
            model_name='house',
            name='caracteristicas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=None, max_length=20), default=None, size=None),
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
            ],
            options={
                'ordering': ('weekday', 'from_hour'),
                'unique_together': {('weekday', 'from_hour', 'to_hour')},
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('phone', models.CharField(max_length=9)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='realEstate.address')),
                ('openingHours', models.ManyToManyField(to='realEstate.openinghours')),
            ],
        ),
    ]
