# Generated by Django 5.0.4 on 2024-04-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0004_address_house_agent_house_caracteristicas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zipCode',
            field=models.IntegerField(default=12345, max_length=5),
        ),
    ]
