# Generated by Django 5.0.4 on 2024-04-23 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0004_officeaddress_useraddress_alter_agent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=120)),
                ('number', models.CharField(max_length=20)),
                ('zipCode', models.IntegerField(default=0)),
                ('localidad', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Direcciones Casa',
            },
        ),
        migrations.DeleteModel(
            name='UserAddress',
        ),
        migrations.RemoveField(
            model_name='house',
            name='city',
        ),
        migrations.RemoveField(
            model_name='house',
            name='country',
        ),
        migrations.RemoveField(
            model_name='house',
            name='zipCode',
        ),
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='realEstate.houseaddress'),
        ),
    ]
