# Generated by Django 5.0.4 on 2024-04-24 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0005_houseaddress_delete_useraddress_remove_house_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='publishedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 24, 11, 15, 17, 423565)),
        ),
        migrations.AlterUniqueTogether(
            name='houseaddress',
            unique_together={('street', 'number', 'zipCode', 'localidad', 'province')},
        ),
        migrations.AlterUniqueTogether(
            name='officeaddress',
            unique_together={('street', 'number', 'zipCode', 'localidad', 'province')},
        ),
    ]
