# Generated by Django 5.0.4 on 2024-04-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0005_address_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipCode',
            field=models.IntegerField(default=12345),
        ),
    ]
