# Generated by Django 5.0.4 on 2024-04-12 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0006_address_province_alter_address_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='oficina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='realEstate.office'),
        ),
    ]
