# Generated by Django 5.0.4 on 2024-04-24 11:26

import datetime
import realEstate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0006_alter_house_publisheddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=realEstate.models.agentFileName),
        ),
        migrations.AlterField(
            model_name='house',
            name='publishedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 24, 13, 26, 12, 348658)),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=realEstate.models.agentFileName),
        ),
    ]
