# Generated by Django 5.0.4 on 2024-04-12 22:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0007_agent_oficina'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='idiomas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), null=True, size=None),
        ),
        migrations.AddField(
            model_name='agent',
            name='photo',
            field=models.ImageField(null=True, upload_to='.agentsPhoto'),
        ),
    ]
