# Generated by Django 5.0.4 on 2024-04-12 22:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0008_agent_idiomas_agent_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='photos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='realEstate/housesPhotos/None'), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='agent',
            name='photo',
            field=models.ImageField(null=True, upload_to='realEstate/agentsPhoto/'),
        ),
    ]
