# Generated by Django 5.0.4 on 2024-05-15 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0010_remove_agent_prueba_alter_house_publisheddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseaddress',
            name='country',
            field=models.CharField(blank=True, default='NULL', max_length=40),
        ),
        migrations.AddField(
            model_name='officeaddress',
            name='country',
            field=models.CharField(blank=True, default='NULL', max_length=40),
        ),
        migrations.AlterField(
            model_name='house',
            name='publishedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 12, 34, 38, 538813)),
        ),
        migrations.AlterField(
            model_name='houseaddress',
            name='province',
            field=models.CharField(blank=True, default='NULL', max_length=50),
        ),
        migrations.AlterField(
            model_name='officeaddress',
            name='province',
            field=models.CharField(blank=True, default='NULL', max_length=50),
        ),
    ]
