# Generated by Django 5.0.4 on 2024-05-15 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0011_houseaddress_country_officeaddress_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='publishedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 13, 33, 31, 241415)),
        ),
        migrations.AlterField(
            model_name='houseaddress',
            name='country',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='houseaddress',
            name='province',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='officeaddress',
            name='country',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='officeaddress',
            name='province',
            field=models.CharField(max_length=50),
        ),
    ]
