# Generated by Django 5.0.4 on 2024-06-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0016_alter_house_publisheddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='construction_year',
            field=models.PositiveIntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='house',
            name='typeHouse',
            field=models.CharField(choices=[('Pisos', [('piso', 'Piso'), ('atico', 'Atico'), ('duplex', 'Duplex')]), ('Casas y Chalets', [('independiente', 'Independiente'), ('pareado', 'Pareado'), ('adosada', 'Adosada'), ('casa_rustica', 'Casa rustica'), ('villa', 'Villa')]), ('Comerciales', [('trastero', 'Trastero'), ('local_comercial', 'Local Comercial')])], max_length=15),
        ),
    ]
