# Generated by Django 5.0.4 on 2024-06-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0017_house_construction_year_alter_house_typehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='floor',
            field=models.CharField(choices=[('last', 'Ultima'), ('middle', 'Intermedias'), ('ground', 'Baja'), ('none', 'None')], max_length=12),
        ),
    ]
