# Generated by Django 5.0.4 on 2024-06-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0018_alter_house_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='typeBusiness',
            field=models.CharField(choices=[('rent', 'Alquilar'), ('sell', 'Vender'), ('transfer', 'Traspasar'), ('sold', 'Vendido')], max_length=10),
        ),
    ]
