# Generated by Django 5.0.4 on 2024-06-13 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0021_agent_bestphrase_agent_linkrrss'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
