# Generated by Django 5.0.4 on 2024-06-13 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0022_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='bestPhrase',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='linkRRSS',
        ),
    ]
