# Generated by Django 5.0.4 on 2024-06-13 18:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0023_remove_agent_bestphrase_remove_agent_linkrrss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='description',
        ),
        migrations.AlterField(
            model_name='agent',
            name='idiomas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='agent',
            name='rol',
            field=models.CharField(max_length=20),
        ),
    ]
